// This file is generated by `ts-rs`. Do not edit this file manually.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiError = { "type": "NetworkError", "message": string } | { "type": "InvalidApiKey" } | { "type": "InvalidApiUrl", "message": string } | { "type": "InvalidModelName", "message": string } | { "type": "RateLimitExceeded" } | { "type": "ApiResponseError", "message": string } | { "type": "InternalError", "message": string };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attachment } from "./Attachment";

export type ConversationMessage = { role: string, content: any, attachment: Attachment | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Attachment = { name: string, type: string, content: string, previewUrl: string | null, };